### ISSUE TITLE
Parking spots under U-Bahn bridge/middle of the street are yet missing

### ISSUE THREAD

**Issue by tifa365** [gislars/osm-parking-processing#33]
Ich weiß nicht ob das noch häufiger vorkommt, im Neukoelln-Projekt sind die Parkplätze  auf der Skalitzer unter der U-Bahn-Brücke gemappt, in diesem hier fehlen sie noch. 

![skalitzer_berlin](https://user-images.githubusercontent.com/66328500/176221543-8b1d5b79-9698-47aa-b421-0184c36e63d1.jpg)
![skalitzer](https://user-images.githubusercontent.com/66328500/176221551-6c59ff93-8340-49a5-b16b-53582206a633.jpg)

https://parkraum.osm-verkehrswende.org/project-vector-tiles/#18/52.499114/13.420729

**Comment by SupaplexOSM** [comment]
Müsste mit dem nächsten Update sichtbar werden - [siehe hier](https://github.com/gislars/strassenraum-berlin/issues/5#issuecomment-1167718049). Dann am besten nochmal prüfen - auch ob die capacity (14) dann korrekt übernommen wird.

**Comment by gislars** [comment]
Die [Straße unter der U-Bahn](https://www.openstreetmap.org/way/866427801) ist mit `service=parking_aisle` getaggt, was ich aber ausschließe. Sind `service=parking_aisle` nicht nur die Wege auf einem Parkplatz?

**Comment by tifa365** [comment]
Ich weiß nicht ob ich auf dem neusten Stand bin. Die Linien erscheinen nach dem Update in hellrot, auch mit der Kapazität, werden aber nicht in dem bekannten Farbchema dargestellt. Um die Kreisel finden sich ein paar Überbleibsel.
![strassenlinien](https://user-images.githubusercontent.com/66328500/180984756-a501a829-c7db-40c8-80e1-17be2f789b4e.jpg)

**Comment by SupaplexOSM** [comment]
Die hellroten Linien sind lediglich die "linken" Seiten der Skalitzer Straße (wo es keine Parkstreifen gibt bzw. die mit "no" getaggt sind). Die Parkbuchten sind noch nicht drin.

**Comment by SupaplexOSM** [comment]
Wir haben uns die Wegsegmente mit `service=parking_aisle` + `parking:lane:<side>` gerade nochmal zusammen angesehen ([Overpass-Abfrage](https://overpass-turbo.eu/s/1kGn)) und sind zum Schluss gekommen, dass der Ausschluss von diesen Segmenten gerechtfertigt ist. Denn es handelt sich in den allermeisten Fällen entweder um eine Fehlverwendung des service=parking_aisle-Tags (so wie in diesem Fall hier) oder um eine Doppel-Information, weil das parking:lane-Schema damit z.B. auf einer bestehenden Parkplatzfläche angewendet wird.

Wir haben festgehalten, dass solche Fälle später einmal in dem Debug-Layer angezeigt werden sollten, um ggf. zu korrigieren.

Ich habe das fehlerhafte Tagging an den hier besprochenen Segmenten nun korrigiert, womit die Parkplätze nach dem nächsten Update einbezogen werden sollten.
